GET "https://prts.wiki/index.php?title=特殊:Cargo导出&tables=chara,chara_data,chara_extra_info,char_obtain,&join+on=chara._pageName=chara_data._pageName,chara._pageName=chara_extra_info._pageName,chara._pageName=char_obtain._pageName&fields=chara._pageName=干员,chara.profession=职业,chara.rarity=稀有度,chara.logo=标志,chara_extra_info.birthPlace=出身地,chara.team=团队,chara_extra_info.race=种族,chara.en=干员西文名,chara.jp=干员日文名,chara.eid=情报编号,chara_extra_info.sex=性别,chara.position=位置,chara.tag=标签,chara.subProfession=子职业,chara.nation=国家,chara.org=组织&where=chara.charIndex>0&order+by=chara.charIndex+ASC&limit=5000&offset=0&format=csv"
